TestMIS/urls.py
from django.conf.urls import patterns, url
from TestMIS import views

urlpatterns = patterns('',
                       url(r'^$', views.IndexView.as_view(), name='index'),
                       # url(r'^mainframe/', views.MfListView.as_view(), name='mainframe_list'),
)

tddunittest/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
# import ../admin as myadmin
from TestMIS.views import IndexView, MfListView, VerListView, ProgListView, TestAnaListView, TestCaseListView, MfDetailView, VerDetailView, ProgDetailView, TestAnaDetailView, TestCaseDetailView, upload_document
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'tddunittest.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    # url(r'^testmis/', include('TestMIS.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', upload_document, name='upload_file'),
    url(r'^place_list/$', MfListView.as_view(), name='place_list'),
    url(r'^version_list/$', VerListView.as_view(), name='ver_list'),
    url(r'^program_list/$', ProgListView.as_view(), name='prog_list'),
    url(r'^testanalysis_list/$', TestAnaListView.as_view(), name='testana_list'),
    url(r'^testcase_list/$', TestCaseListView.as_view(), name='testcase_list'),
    url(r'^place/(?P<pk>[-_\w]+)/$', MfDetailView.as_view(), name='place_detail'),
    url(r'^version/(?P<pk>\d+)/$', VerDetailView.as_view(), name='ver_detail'),
    url(r'^program/(?P<pk>\d+)/$', ProgDetailView.as_view(), name='prog_detail'),
    url(r'^testanalysis/(?P<pk>\d+)/$', TestAnaDetailView.as_view(), name='testana_detail'),
    url(r'^testcase/(?P<pk>\d+)/$', TestCaseDetailView.as_view(), name='testcase_detail'),
) + static(settings.DOCUMENT_URL, document_root=settings.DOCUMENT_ROOT)

TestMIS/models.py
# -*-coding:utf-8 -*-
from django.db import models
from django.core.validators import RegexValidator


class Place(models.Model):
    name = models.CharField(
        verbose_name='主机名',
        help_text='D3/D4/D5...等主机名称',
        max_length=10,
        primary_key=True,
    )
    ip = models.IPAddressField(
        verbose_name='IP地址',
        help_text='主机对应的IP地址',
    )
    port = models.IntegerField(
        verbose_name='IP端口(默认为0)',
        default=0,
        help_text='主机PCOM的IP端口',
    )

    class Meta:
        verbose_name = "主机"
        verbose_name_plural = "主机列表"

    def __unicode__(self):
        return u"{0} - IP: {1}".format(self.name, self.ip)


class Program(models.Model):
    PDS_LIST = (
        'ONL.COB.SRC', 'COM.COB.SRC', 'BTCH.COB.SRC',
        'ONL.MVSCOB.SRC', 'COM.MVSCOB.SRC', 'BTCH.MVSCOB.SRC',
        )
    PDS_CHOICES = ((x, x) for x in PDS_LIST)
    name = models.CharField(
        verbose_name='程序名',
        max_length=12,
    )
    pds = models.CharField(
        verbose_name='PDS',
        max_length=20,
        choices=PDS_CHOICES,
    )

    class Meta:
        verbose_name = "程序"
        verbose_name_plural = "程序列表"

    def __unicode__(self):
        return u"{0}({1})".format(self.pds, self.name)


class Version(models.Model):

    name = models.CharField(
        verbose_name='批次号',
        max_length=4,
    )
    place = models.ForeignKey(
        verbose_name='主机环境',
        to=Place,
    )
    alias = models.CharField(
        verbose_name='主机环境前缀',
        max_length=4,
    )

    class Meta:
        verbose_name = "批次"
        verbose_name_plural = "批次列表"

    def __unicode__(self):
        return u"{0}批次: {2} on ({1})".format(self.name, self.place, self.alias)


class TestAnalysis(models.Model):

    version = models.ForeignKey(Version)
    program = models.ForeignKey(Program)

    class Meta:
        verbose_name = "测试分析"
        verbose_name_plural = "测试分析"

    def __unicode__(self):
        return u"{0} - {1}{2} ({3})".format(
            self.program.name, self.version.alias, self.program.pds,
            self.version.name,
            )


class TestCase(models.Model):
    CASE_TYPE = (
        ('B', '基础案例'),
        ('E', '扩展案例'),
    )
    (BASE_CASE, EXTEND_CASE,) = ('B', 'S',)
    test_analysis = models.ForeignKey(
        verbose_name='测试分析',
        to=TestAnalysis,
    )
    model_in_program = models.CharField(
        verbose_name='模块名',
        max_length=100
    )
    case_no = models.CharField(
        verbose_name='案例号',
        max_length=8,
        validators=[RegexValidator(regex=r'CASE\d{4,4}'), ]
    )
    case_type = models.CharField(
        verbose_name='案例类型',
        max_length=1,
        choices=CASE_TYPE,
    )
    base_case = models.ForeignKey(
        verbose_name='关联基础案例号',
        to='self',
        null=True,
        blank=True,
    )
    case_div = models.CharField(
        verbose_name='基础案例划分',
        max_length=200,
        blank=True,
    )
    designer = models.CharField('设计者', max_length=15)
    case_explain = models.TextField('案例注解')
    case_aim = models.TextField('测试目标')

    class Meta:
        verbose_name = "测试案例"
        verbose_name_plural = "测试案例列表"

    def is_base_case(self):
        return self.case_type == TestCase.BASE_CASE

    def is_extend_case(self):
        return not self.is_base_case()

    def get_readonly_fields(self):
        readonly_fileds = ['test_analysis', 'designer']
        if self.is_base_case():
            readonly_fileds.append('base_case')
        else:
            readonly_fileds.append('case_div')
        # readonly_fileds.append('case_type')
        return readonly_fileds

    def query_base_cases(self):
        return TestCase.objects.filter(
            test_analysis=self.test_analysis, case_type=TestCase.BASE_CASE)

    def __unicode__(self):
        return u"{0}-{1}".format(self.test_analysis.program.name, self.case_no)


class TestPoint(models.Model):
    POINT_TYPE = (
        ('I', u'输入'),
        ('O', u'输出')
    )
    test_case = models.ForeignKey(
        verbose_name='测试案例',
        to=TestCase,
    )
    point_name = models.CharField(
        verbose_name='切片标签',
        max_length=30,
    )
    point_type = models.CharField(
        verbose_name='类型',
        max_length=1,
        choices=POINT_TYPE,
    )
    var_name = models.CharField(
        verbose_name='变量',
        max_length=30,
    )
    var_comment = models.CharField(
        verbose_name='变量注解',
        max_length=200,
    )
    var_value = models.CharField(
        verbose_name='输入值/观测值',
        max_length=254)

    class Meta:
        verbose_name = u"测试点"
        verbose_name_plural = u"测试点"

    def __unicode__(self):
        return u"{0}-TDDLBL:{1},TYPE:{2},VAR:{3}".format(
            self.test_case,
            self.point_name,
            self.point_type,
            self.var_name,
        )


class ExcelCol(models.Model):

    sheet_name = models.CharField(
        verbose_name='对应的sheet',
        max_length=21,
        help_text='excel中sheet的名字',
        default='单元测试分析',
    )

    col_name = models.CharField(
        verbose_name='列名',
        max_length=20,
        help_text='组成测试分析or案例所必要的列',
    )

    col_pos_x = models.IntegerField(
        verbose_name='第N列',
        help_text='本列在规定的excel格式要求内的列号，从1开始计算',
    )

    class Meta:
        verbose_name = "Excel格式定义"
        verbose_name_plural = "Excel格式定义列表"
        ordering = ['sheet_name', 'col_pos_x']
        # unique_together = (('sheet_name', 'col_pos_x'),)

    def __unicode__(self):
        return u"{0}'s {1} Col at {2} pos.".format(
            self.sheet_name,
            self.col_name,
            self.col_pos_x,
        )


class ExcelContraint(models.Model):

    CONSTRAINT_TYPE = (
        ('R', '正则表达式'),
        ('L', '列表'),
        ('C', 'COBOL子句'),
        ('S', '不允许有空格'),
        ('O', '非空值'),
        ('X', '替换值'),
        ('N', '允许空值'),
        ('M', '关联约束'),
    )

    (
        REGEX, LIST, CLAUSE, NON_SPACE, NOT_NULL,
        REPLACE, NULL, MULTI_CONSTRAINT,
    ) = (
        'R', 'L', 'C', 'S', 'O', 'X', 'N', 'M',
    )

    excel_col = models.ForeignKey(
        verbose_name='添加约束的列',
        to=ExcelCol,
        null=True  # 不设置这个的话，在 makemigrations TestMIS 时会提示 trying to add a non-nullable
                   # field 'excel_col' to excelcontraint without a default
    )

    constraint_type = models.CharField(
        verbose_name='约束类型',
        max_length=1,
        choices=CONSTRAINT_TYPE,
    )

    regrex_formula = models.CharField(
        verbose_name='正则表达式',
        max_length=100,
        help_text='仅当约束类型选择“正则表达式”时生效',
        null=True,
        blank=True,
    )

    x_from = models.CharField(
        verbose_name='替换原值',
        max_length=100,
        help_text='仅当约束类型选择“替换值”时有效',
        null=True,
        blank=True,
    )
    x_to = models.CharField(
        verbose_name='替换目标',
        max_length=100,
        help_text='仅当约束类型选择“替换值”时有效',
        null=True,
        blank=True,
    )
    within_list = models.CharField(
        verbose_name='枚举列表',
        max_length=200,
        validators=[RegexValidator(regex=r'(?:\S+?, ?)+'), ],
        help_text='仅当约束类型选择“列表”时有效',
        null=True,
        blank=True,
    )
    relative_from = models.ForeignKey(
        verbose_name='依赖列',
        to=ExcelCol,
        related_name='dependency col',
        null=True,
        blank=True,
    )
    relative_value = models.CharField(
        verbose_name='依赖列的取值',
        max_length=100,
        null=True,
        blank=True,
    )
    relative_constraint = models.CharField(
        verbose_name='依赖约束',
        max_length=100,
        null=True,
        blank=True,
    )

    class Meta:
        verbose_name = "ExcelContraint"
        verbose_name_plural = "ExcelContraints"

    def __unicode__(self):
        return u"col {0}'s contraint: {1}".format(
            self.excel_col.col_name,
            self.constraint_type,
        )

class Document(models.Model):
    docfile = models.FileField(
        verbose_name="选择文件",
        upload_to='documents/%Y/%m/%d'
    )

    class Meta:
        verbose_name="上传文件"
        verbose_name_plural="上传文件"

    def __unicode__(self):
        return self.docfile.url

class Report(models.Model):
    execute_date = models.DateField(verbose_name="执行日期")
    execute_time = models.TimeField(verbose_name="执行时间")
    driven_trade = models.CharField(
        verbose_name="驱动交易",
        max_length=20
    )
    # test_program = models.CharField(
    #     verbose_name="测试程序",
    #     max_length=10,
    #     blank=True
    # )
    test_teller = models.CharField(
        verbose_name="测试柜员",
        max_length=20
    )
    # case_no = models.CharField(
    #     verbose_name="案例号",
    #     max_length=20,
    #     blank=True
    # )
    test_point = models.ForeignKey(
        verbose_name="测试点",
        to=TestPoint
    )
    STATUS_CHOICES = (
        ('B', u'(空白)'),
        ('Y', u'成功'),
        )
    status = models.CharField(
        verbose_name="是否成功",
        max_length=10,
        choices=STATUS_CHOICES,
    )
    # var_observed=models.CharField(
    #     verbose_name="观测变量",
    #     max_length=50
    # )
    actual_value=models.CharField(
        verbose_name="实际值",
        max_length=20,
    )
    # predict_value=models.FloatField(
    #     verbose_name="预期值",
    #     default=0.0
    # )

    class Meta:
        unique_together=(("execute_date", "execute_time", "test_point"),)
        # unique_together=(("test_point.test_case.test_analysis.program.name",
        #                   "test_point.test_case.case_no",
        #                   "test_point"
        # ),)
        verbose_name=u"单元测试报表"
        verbose_name_plural=u"单元测试报表"

    def __unicode__(self):
        return u"{0}-{1}-{2}".format(self.execute_date, self.execute_time, self.test_point)

    # def save(self):
    #     self.test_program = self.test_point.test_case.test_analysis.program.name

templates/base.html
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>CobolTDD</title>

    {% load staticfiles %}
    {% block css %}
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'TestMIS/django_tables2/themes/paleblue/css/screen.css' %}" /> -->
    <link rel="stylesheet" type="text/css" href="{% static 'TestMIS/bootstrap.min.css' %}" />
    {% endblock %}
</head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <!-- <a class="navbar-brand" href="{}">主机列表</a> -->
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                {% if user.is_authenticated %}
                <li><a href="#"> 欢迎 {{ user.username }}</a></li>
                    <li><a href="{% url 'upload_file' %}">上传文件</a></li>
                    <li><a href="{% url 'place_list' %}">主机列表</a></li>
                    <li class=""><a href="{% url 'ver_list' %}">批次列表</a></li>
                    <li><a href="{% url 'testana_list' %}">测试分析</a></li>
                <li><a href="{% url 'testcase_list' %}">测试案例分析</a></li>
                <li><a href="{% url 'prog_list' %}">程序列表</a></li>
                {% else %}
                <li><a href="{% url 'upload_file' %}">上传文件</a><li>
                <li><a href="{% url 'place_list' %}">主机列表</a></li>
                    <li class=""><a href="{% url 'ver_list' %}">批次列表</a></li>
                    <li><a href="{% url 'testana_list' %}">测试分析</a></li>
                <li><a href="{% url 'testcase_list' %}">测试案例分析</a></li>
                <li><a href="{% url 'prog_list' %}">程序列表</a></li>
                    <!-- <li class=""><a href='{}'>批次列表</a></li> -->
                    <!-- <li><a href="{}">测试分析</a></li> -->
                    <!-- <li><a href="{}">测试案例列表</a></li> -->
                    <!-- <li><a href="{}">程序列表</a></li> -->
                {% endif %}
                <!-- <li><a href="{}">Feed</a></li> -->
            </ul>
        </div>
        <!--/.nav-collapse -->
    </div>
</nav>

<br/>
<br/>
<br/>

<div class="container">

    <div class="starter-template">
        {#        {% if messages %}#}
        {#            <ul class="messages">#}
        {#                {% for message in messages %}#}
        {#                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>#}
        {#                        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}#}
        {#                        {{ message }}#}
        {#                    </li>#}
        {#                {% endfor %}#}
        {#            </ul>#}
        {#        {% endif %}#}
        {#        <h1>Bootstrap starter template</h1>#}
        {#        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>#}
        {% block content %}
        {% endblock %}

    </div>

</div>
<!-- /.container -->

{% block scripts %}
<!-- <script src="//tinymce.cachefly.net/4.1/tinymce.min.js"></script> -->
<!-- <script src="tinymce.min.js"></script> -->
    <!-- <script>tinymce.init({selector: 'textarea'});</script> -->
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script> -->
    <!-- <script src="jquery.min.js"></script> -->
    <!-- Latest compiled and minified CSS -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css"> -->
    <!-- {% load staticfiles %} -->
    <!-- <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" /> -->

    <!-- Optional theme -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css"> -->
    <!-- <link rel="stylesheet" href="bootstrap-theme.min.css"> -->

    <!-- Latest compiled and minified JavaScript -->
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script> -->
    <!-- <script src="bootstrap.min.js"></script>  -->

{% endblock %}


</body>
</html>

templates/place_detail.html
{% extends 'base.html' %}

{% block content %}
{% if place_detail %}

  <h3>主机名：{{ place_detail.name }}</h3><br>
  <h3>IP地址：{{ place_detail.ip }}</h3><br>
  <h3>IP端口(默认为0)：{{ place_detail.port }}</h3>


{% endif %}
{% endblock %}

templates/place_list.html
{% extends 'base.html' %}
{% block content %}
<h2> 主机：</h2>
<ul>
  {% for place in place_list %}
  <li>
    <a href="{% url 'place_detail' place.name %}">
      <!-- <h3>{{ place.name }}-{{ place.ip }}: {{ place.port }}</h3> -->
      <!-- <h3>{{ mainframe.objects.all }}</h3> -->
      <h3>{{ place }}</h3>
    </a>
  </li>
  {% endfor %}
</ul>
{% endblock %}

templates/program_detail.html
{% extends 'base.html' %}
{% block content %}

{% if program_detail %}

  <h3>程序名：{{ program_detail.name }}</h3><br>
  <h3>PDS：{{ program_detail.pds }}</h3>

{% endif %}

{% endblock %}

templates/program_list.html
{% extends 'base.html' %}
{% block content %}
<h2>程序：</h2>
{% if program_list %}
<ul>
  {% for prog in program_list %}
  <li>
    <a href="{% url 'prog_detail' prog.id %}">
      <!-- <h3>{{ prog.pds }} ({{ prog.name }})</h3> -->
      <h3>{{ prog }}</h3>
    </a>
  </li>
</ul>
{% endfor %}
{% endif %}
{% endblock %}

templates/testanalysis_detail.html
{% extends 'base.html' %}

{% block content %}

{% if testanalysis_detail %}

  <h3>批次：{{ testanalysis_detail.version }}</h3><br>
  <h3>程序：{{ testanalysis_detail.program }}</h3>

{% endif %}

{% endblock %}

templates/testanalysis_list.html
{% extends 'base.html' %}
{% block content %}
<h2>测试分析：</h2>
{% if testanalysis_list %}
<ul>
  {% for testanalysis in testanalysis_list %}
  <li>
    <a href="{% url 'testana_detail' testanalysis.id %}">
      <!-- <h3>{{ testanalysis.program.name }} - {{ testanalysis.version.alias }}{{ testanalysis.program.pds }} ({{ testanalysis.version.name }})</h3> -->
      <h3>{{ testanalysis }}</h3>
    </a>
  </li>
  {% endfor %}
</ul>
{% endif %}
{% endblock %}

templates/testcase_detail.html
{% extends 'base.html' %}

{% block content %}

{% if testcase_detail %}
<table>
  <tr>
    <td><font size="5" color="blue">归属&nbsp&nbsp</font></td>
    <!-- <td><input type="submit", name="addtestcase" value="Add" onclick="window.location.href('admin/TestMIS/testcase/add?tc_pk={{ testcase_detail.pk }}')"></td> -->
    <td><a href='/admin/TestMIS/testcase/add/?tc_pk={{ testcase_detail.pk }}'>添加测试案例</a></td>
  </tr>
</table>
  <h3>测试分析：{{ testcase_detail.test_analysis }}</h3><br>

  <font size="5" color="blue">基本信息</font><br>
  <h3>模块名：{{ testcase_detail.model_in_program }}</h3><p>
  <h3>案例号：{{ testcase_detail.case_no }}</h3><p>
  <h3>设计者：{{ testcase_detail.designer }}</h3><br>

<table>
  <tr>
  <td><font size="5" color="blue">案例继承&nbsp&nbsp</font><br></td>
  {% if testcase_detail.case_type == 'B' %}
  <td><a href='/admin/TestMIS/testcase/add/?base_pk={{ testcase_detail.pk }}'>添加扩展案例</a></td>
  {% endif %}
  </tr>
</table>
  <p><h3>案例类型：
   {{ testcase_detail.get_case_type_display }}</h3></p>
  <h3>关联基础案例号：{{ testcase_detail.base_case }}</h3><p>
  <h3>基础案例划分：{{ testcase_detail.case_div }}</h3><br>

  <font size="5" color="blue">案例说明</font><br>
  <h3>案例注释：{{ testcase_detail.case_explain }}</h3><p>
  <h3>测试目标：{{ testcase_detail.case_aim }}</h3><br>

  <font size="5" color="blue">测试点</font><br>
  <table>
    <tr>
      <th><h3>切片标签&nbsp&nbsp&nbsp&nbsp&nbsp</h3></th>
      <th><h3>类型&nbsp&nbsp&nbsp&nbsp&nbsp</h3></th>
      <th><h3>变量&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</h3></th>
      <th><h3>变量注解&nbsp&nbsp&nbsp&nbsp&nbsp</h3></th>
      <th><h3>输入值/观测值</h3></th>
    </tr>
    {% if testcase_detail.testpoint_set.all %}
    {% for testpoint in testcase_detail.testpoint_set.all %}
    <tr>
      <td><h3>{{ testpoint.point_name }}</h3></td>
      <td>
          <h3>{{ testpoint.get_point_type_display }}</h3>
      </td>
      <td><h3>{{ testpoint.var_name }}</h3></td>
      <td><h3>{{ testpoint.var_comment }}</h3></td>
      <td><h3>{{ testpoint.var_value }}</h3></td>
    </tr>
    {% endfor %}
    {% endif %}
  </table>
{% endif %}

{% endblock %}

templates/testcase_list.html
{% extends 'base.html' %}

{% block content %}
<table>
  <tr>
    <th scope="col"><h2> 案例号&nbsp&nbsp&nbsp&nbsp&nbsp </h2></th>
    <th scope="col"><h2> 案例类型&nbsp&nbsp&nbsp&nbsp&nbsp </h2> </th>
    <th scope="col"><h2> 测试分析 </h2> </th>&nbsp
  </tr>
  {% if testcase_list %}
    {% for testcase in testcase_list %}
    <tr>
    <td><a href="{% url 'testcase_detail' testcase.pk %}"><h3>{{ testcase.case_no }}</h3></a></td>
    {% if testcase.is_base_case %}
    <td><h3>基础案例</h3></td><p>
        {% else %}
    <td><h3>扩展案例</h3></td>
    {% endif %}
    <td><h3>{{ testcase.test_analysis }}</h3></td>
  </tr>
    {% endfor %}
    {% endif %}
</table>
{% endblock %}

templates/upload_file.html
{% extends 'base.html' %}

{% block content %}
<h3>上传文件</h3>

{% if documents %}
<ul>
  {% for document in documents %}
  <li><a href="{{ document.docfile.url }}">{{ document.docfile.name }}</a></li>
  {% endfor %}
</ul>
{% endif %}

<form action="{% url 'upload_file' %}" method="post" enctype="multipart/form-data" >
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Upload"/>
</form>
{% endblock %}

templates/version_detail.html
{% extends 'base.html' %}
{% block content %}

{% if version_detail %}

  <h3>批次号：{{ version_detail.name }}</h3><br>
  <h3>主机环境：{{ version_detail.place }}</h3><br>
  <h3>主机环境前缀：{{ version_detail.alias }}</h3>

{% endif %}

{% endblock %}

templates/version_list.html
{% extends 'base.html' %}
{% block content %}
<h2>批次：</h2>
{% if version_list  %}
<ul>
  {% for ver in version_list %}
  <li>
    <a href="{% url 'ver_detail' ver.id %}">
      <!-- <h3>{{ ver.name }} 批次：{{ ver.alias }} on ({{ ver.place }})</h3> -->
      <h3>{{ ver }}</h3>
    </a>
  </li>
  {% endfor %}
</ul>
{% endif %}
{% endblock %}